modLoader = "javafml"
loaderVersion = "[36,)"
license = "GNU General Public License v3.0"

[[mods]]
modId = "eos"
version = "${file.jarVersion}"
displayName = "Evolution Of Sugar"
displayURL = "https://github.com/SugarWorkshop/Evolution-Of-Sugar/"
authors = "SugarMGP"
description = '''A mod that commemorate the Sugar Meow Group's members.'''

[[dependencies.eos]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.eos]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
