# This workflow will build a Java project with Gradle

name: EOS Snapshot Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone EOS Repository
        uses: actions/checkout@v4.1.1
        with:
          repository: SugarWorkshop/Evolution-Of-Sugar
          ref: 1.16.5
          path: EOS-1.16

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Grant Execute Permission
        run: chmod +x ./EOS-1.16/gradlew

      - name: Build
        run: cd ./EOS-1.16/ && ./gradlew build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.0
        with:
          name: EOS Snapshot
          path: ./EOS-1.16/build/libs

      - name: Package Release
        if: ${{github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')}}
        run: |
          mkdir EOS-Build
          mv ./EOS-1.16/build/libs/* ./EOS-Build
          tar -cvf EOS-Build.tar ./EOS-Build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v0.1.15
        if: ${{github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          prerelease: true
          files: EOS-Build.tar
          body: |
            ## 更新日志
            * 这是 GitHub Action 自动化部署，更新日志将会手动更新。
